Contrib guide en
x-orpheus/svrx-docs pull request #12
Opened 2019-09-10 13:15 UTC by leeluolee

2019-09-11 15:29 UTC, int64ago commented on en/README.md
> +![](https://p1.music.126.net/-ZK3lYZLWMHfPkXi7nn_gg==/109951164332910231.gif)
- Open Chrome in `incognito mode` for privacy
 - Set VSCode language to English

2019-09-11 15:29 UTC, int64ago commented on en/README.md
> +To solve the problem, we plan to integrate all the development services into a pluggable platform,
`development services` -> `development services and tools`

2019-09-11 15:29 UTC, int64ago commented on en/README.md
> +View [guide section](./guide/README.md) for suggestion.
`for suggestion` -> `for more details`

2019-09-11 15:29 UTC, int64ago commented on en/contribute/plugin.md
> +1. `configSchema` Plugin param definition based json-schema ，checkout [json-schema](#schema) for more detail.
`based json-schema` -> `based on JSON Schema`

2019-09-11 15:29 UTC, int64ago commented on en/contribute/plugin.md
> +     > All resources will be merged into one link
`a single file` is better than `one link` ?

2019-09-11 15:29 UTC, int64ago commented on en/contribute/plugin.md
> +3. `hook.onCreate`: a function invoke when plugin been creating, we can control it by injected service
`a function invoke when plugin been creating, we can control it by injected service`

->

`a function invoked during plugin initialization, we can overwrite it by injected services`

2019-09-11 15:29 UTC, int64ago commented on en/contribute/plugin.md
> +   in this example, we only use two service
`two service` -> `two services`

2019-09-11 15:29 UTC, int64ago commented on en/contribute/plugin.md
> +There is a global variable named `svrx` wiil be injected to every page,
`wiil be injected to every page` -> `will be injected into all pages`

2019-09-11 15:29 UTC, int64ago commented on en/contribute/plugin.md
> +When try to publish package by `npm publish`， we will find it fails. beacuse `svrx-plugin-hello-world` has beed published by [offical team](https://github.com/svrxjs/svrx-plugin-hello-world)
`When try to publish package by `npm publish`， we will find it fails.`

->

`There'll be a failure when trying to publish ...`

2019-09-11 15:29 UTC, int64ago commented on en/contribute/plugin.md
> +check the terminal and browser console log, we will find `Hello svrx from browser`.
`check` -> `Check`

2019-09-11 15:29 UTC, int64ago commented on en/contribute/plugin.md
> +You can also run it by programmatical way
`by` -> `in`

2019-09-11 15:30 UTC, int64ago commented
Review is still in process...

2019-09-12 02:06 UTC, leeluolee commented on en/contribute/plugin.md
> +When try to publish package by `npm publish`， we will find it fails. beacuse `svrx-plugin-hello-world` has beed published by [offical team](https://github.com/svrxjs/svrx-plugin-hello-world)
very good.

2019-09-12 02:48 UTC, leeluolee commented on en/README.md
> +![](https://p1.music.126.net/-ZK3lYZLWMHfPkXi7nn_gg==/109951164332910231.gif)
approve

2019-09-12 02:48 UTC, leeluolee commented on en/README.md
> +View [guide section](./guide/README.md) for suggestion.
fixed

2019-09-12 02:48 UTC, leeluolee commented on en/contribute/plugin.md
> +1. `configSchema` Plugin param definition based json-schema ，checkout [json-schema](#schema) for more detail.
fixed

2019-09-12 02:48 UTC, leeluolee commented on en/contribute/plugin.md
> +     > All resources will be merged into one link
agree

2019-09-12 04:19 UTC, leeluolee commented on en/contribute/plugin.md
> +There is a global variable named `svrx` wiil be injected to every page,
fixed

2019-09-22 06:19 UTC, int64ago commented on en/contribute/plugin.md
> +参数定义
?

2019-09-22 06:19 UTC, int64ago commented on en/contribute/plugin.md
> +There is a global variable named `svrx` wiil be injected into all pages,
wiil -> will

2019-09-22 06:19 UTC, int64ago commented on en/contribute/plugin.md
> +获取一个插件配置
?

2019-09-23 03:17 UTC, dayjoyx requested changes

2019-09-23 03:17 UTC, dayjoyx commented on en/contribute/plugin.md
> +- `engines.svrx`: Define the runnable svrx version of this plugin，svrx will automatically load the latest matching plugin
> svrx will automatically load the latest matching plugin

missing a comma maybe？

2019-09-23 03:17 UTC, dayjoyx commented on en/contribute/plugin.md
> +Check out setion [service](#server) to find other services that available in `hook.onCreate`
to find other services that available in `hook.onCreate`

-> 

to find out other services available in `hook.onCreate`

2019-09-23 03:17 UTC, dayjoyx commented on en/contribute/plugin.md
> +There'll be a failure when trying to publish it by `npm publish`. beacuse `svrx-plugin-hello-world` has beed published by [offical team](https://github.com/svrxjs/svrx-plugin-hello-world)
beacuse `svrx-plugin-hello-world` has beed published

->

Beacuse `svrx-plugin-hello-world` has beed published

2019-09-23 03:17 UTC, dayjoyx commented on en/contribute/plugin.md
> +Check the terminal and browser console log, we will find `Hello svrx from browser`.
maybe a comma in the end of line?

2019-09-23 03:17 UTC, dayjoyx commented on en/contribute/plugin.md
> +  been injected before the closing 'head` tag
~~been~~ injected before the closing `head` tag

2019-09-23 03:17 UTC, dayjoyx commented on en/contribute/plugin.md
> +  been injected before the closing 'head` tag
and don't forget the  'head`

2019-09-23 03:17 UTC, dayjoyx commented on en/contribute/plugin.md
> +  been injected before the closing 'body` tag
same as above

2019-09-23 03:17 UTC, xuchaoying commented on en/contribute/plugin.md
> +events.on('hello'); // remove all hello's handler
events.off

2019-09-23 03:17 UTC, xuchaoying commented on en/contribute/plugin.md
> +events.on('hello', handler); // remove specific handler
events.off

2019-09-23 03:17 UTC, xuchaoying commented on en/contribute/plugin.md
> +Register a action , like [`proxy`](../guide/route.md#proxy) or [`json`](../guide/route.md#json)
a action  -> an action

2019-09-23 03:17 UTC, xuchaoying commented on en/contribute/plugin.md
> +io used for the communication between server and client ， Please check it with [client-side io](#client-io)
io is used for the communication between server and client. Please check it out in [client-side io](#client-io)

2019-09-23 03:17 UTC, xuchaoying commented on en/contribute/plugin.md
> +解除监听
no Chinese

2019-09-23 03:17 UTC, xuchaoying commented on en/contribute/plugin.md
> +- `type` \[String]: [JSON-Schema field type](https://json-schema.org/understanding-json-schema/reference/type.html) ，可以是`array`、`string`、`number`、`boolean`、`object`、`null`
`可以是 `

2019-09-23 03:17 UTC, xuchaoying commented on zh/contribute/plugin.md
> +=======
these 2 lines should be removed?

2019-09-24 06:26 UTC, xuchaoying commented on en/contribute/plugin.md
> +There'll be a failure when trying to publish it by `npm publish`. beacuse `svrx-plugin-hello-world` has beed published by [offical team](https://github.com/svrxjs/svrx-plugin-hello-world)
has been

2019-09-24 07:06 UTC, leeluolee commented on en/contribute/plugin.md
> +参数定义
already removed all `[ \u4e00-\u9fa5]`

2019-09-24 07:07 UTC, leeluolee commented on en/contribute/plugin.md
> +There is a global variable named `svrx` wiil be injected into all pages,
fixed

2019-09-24 07:53 UTC, int64ago approved these changes

2019-09-24 08:04 UTC, dayjoyx approved these changes

2019-09-24 08:05 UTC, merged